title: 🐟
email: cetaSYN@nom.fish
description: >- # this means to ignore newlines until "baseurl:"
  Net/Sec/Dev
baseurl: ""
url: "https://www.nom.fish"
twitter_username: cetaSYN
github_username:  cetaSYN

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed